[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OpenWiki"
authors = [{name = "Earth1283"}]
version = "0.1.0"
description = "An uncensored wiki for server ownership for Minecraft: Java Edition"
